name: Sync images Test

on:
  push:
    branches:
      - master

jobs:
  gcr-to-aliyun:
    runs-on: ubuntu-20.04
    container: setzero/images-sync:0.3.2
    env:
      TO_USERNAME: ${{ secrets.TO_USERNAME }}
      TO_PASSWORD: ${{ secrets.TO_PASSWORD }}
    steps:
      - name: Gcr to Registry
        run: |
          cat << EOF >config.yaml
          from:
            registry: https://k8s.gcr.io
          to:
            registry: https://harbor.prod.k8s.lesso.com
          names:
            - pause
            - etcd
          replace:
            - new: kubeadm-ha
          rules:
            - ^[Vv]?\d+\.\d+(\.\d+)?(-\d+)?$
          EOF
          sync-images --config config.yaml
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 3

